// src/components/Counter.tsx
import { useState } from "react";
// import styles from './Counter.module.scss';

export const Counter: React.FC<{ initial?: number }> = ({ initial }) => {
  const [count, setCount] = useState(initial ?? 0);

  return (
    <div>
      <div data-testid="count">{count}</div>
      <button onClick={() => setCount(count + 1)}>Increment</button>
      <button onClick={() => setCount(count + 1)}>Decrement</button>
    </div>
  );
}

// test-projects/vite-vue/src/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue'

const { initial } = defineProps<{ initial: number }>()

const count = ref(initial ?? 0)
</script>

<template>
  <div className={styles.counter}>
    <div data-testid="count">{{count}}</div>
    <button @click=count++>Increment</button>
    <button @click=count-->Decrement</button>
  </div>
</template>
