// test-projects/speed-comparison/src/Counter.tsx
import { useState } from "react";

export const Counter: React.FC<{ initial?: number }> = ({ initial }) => {
  const [count, setCount] = useState(initial ?? 0);

  return (
    <div>
      <div data-testid="count">{count}</div>
      <button onClick={() => setCount(count + 1)}>Increment</button>
      <button onClick={() => setCount(count - 1)}>Decrement</button>
    </div>
  );
}

// test-projects/vite-svelte/src/lib/Counter.svelte
<script lang="ts">
	let { initial } = $props();
  let count: number = $state(initial ?? 0)
  const increment = () => {
    count += 1
  }
  const decrement = () => {
    count -= 1
  }
</script>

<div>
  <div data-testid="count">{count}</div>
  <button onclick={increment}>Increment</button>
  <button onclick={decrement}>Decrement</button>
</div>
